/** Apply the approved SERI layout after the existing dependency-free content build.
 * Source records, form modes, metadata, exports and route generation remain owned
 * by build.mjs. This step changes presentation only, and fails on template drift.
 */
import './build.mjs';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'dist');
const load=n=>JSON.parse(fs.readFileSync(path.join(root,'site/content',n+'.json'),'utf8'));
const site=load('site'),projects=load('projects'),papers=load('publications');
const dataset=load('data-explorer').find(d=>d.id==='germany-published');
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>(n<0?'−':n>0?'+':'')+Math.abs(n).toFixed(2);
const outcomes=[6,7,8,9].map(i=>dataset.variables[i].label.replace('wellbeing','well-being'));
const series=Object.fromEntries([3,4,5].map(i=>[String(i),{label:dataset.variables[i].label,values:[6,7,8,9].map(j=>{const p=dataset.groups[0].pairs[`${i}|${j}`];assert.ok(Number.isFinite(p.pearson)&&p.ci?.length===2,'Published chart source is incomplete');return[p.pearson,...p.ci];})}]));
const link=(href,label)=>`<a class="text-link" href="${href}">${label} <span aria-hidden="true">→</span></a>`;
function once(html,re,value,label){assert.equal([...html.matchAll(new RegExp(re.source,re.flags.includes('g')?re.flags:re.flags+'g'))].length,1,`Unexpected ${label} template`);return html.replace(re,value);}
function svg(values){const X=r=>210+(r+.6)/1.2*365;let s='<svg class="ser-forest" viewBox="0 0 650 272" role="img" aria-label="Published Pearson correlations. Exact values and confidence intervals are in the table below.">';
 for(const t of [-.6,-.3,0,.3,.6])s+=`<line x1="${X(t)}" x2="${X(t)}" y1="18" y2="215" class="${t===0?'ser-zero':'ser-grid'}"/><text x="${X(t)}" y="237" text-anchor="middle" class="ser-axis">${t===0?'0':fmt(t)}</text>`;
 values.forEach(([r,lo,hi],i)=>{const y=43+i*49;s+=`<text x="0" y="${y+5}" class="ser-outcome">${E(outcomes[i])}</text><path class="ser-ci" d="M${X(lo)} ${y-5}V${y+5}M${X(lo)} ${y}H${X(hi)}M${X(hi)} ${y-5}V${y+5}"/><circle class="ser-dot" cx="${X(r)}" cy="${y}" r="5.5"><title>${E(outcomes[i])}: r = ${r.toFixed(2)}; 95% CI [${lo.toFixed(2)}, ${hi.toFixed(2)}]</title></circle><text class="ser-value" x="630" y="${y+5}" text-anchor="end">${fmt(r)}</text>`;});
 return s+'<text class="ser-axis" x="392" y="265" text-anchor="middle">Pearson correlation (r)</text></svg>';}
function chart(id){const s=series['3'];return `<div class="ser-chart" data-ser-chart data-series="${E(JSON.stringify(series))}" data-outcomes="${E(JSON.stringify(outcomes))}"><div class="ser-chart-heading"><div><p class="eyebrow">Published findings</p><h3>Antisemitism and well-being</h3></div><span>Germany · Survey N = ${dataset.groups[0].n}</span></div><div class="ser-controls"><label>Antisemitism measure<select id="${id}-measure" data-ser-measure>${Object.entries(series).map(([k,s])=>`<option value="${k}">${E(s.label)}</option>`).join('')}</select></label><label class="ser-check"><input type="checkbox" data-ser-ci checked> 95% confidence intervals</label></div><div class="ser-plot">${svg(s.values)}</div><p class="ser-reading" aria-live="polite">${E(s.label)}: r = ${s.values.map(v=>fmt(v[0])).join(', ')} for well-being, anxiety, depression, and social participation, respectively.</p><details class="ser-table"><summary>View values in a table</summary><div class="table-scroll"><table><caption>${E(s.label)}: published correlations</caption><thead><tr><th scope="col">Outcome</th><th scope="col">r</th><th scope="col">95% CI</th></tr></thead><tbody>${s.values.map(([r,lo,hi],i)=>`<tr><th scope="row">${E(outcomes[i])}</th><td>${fmt(r)}</td><td>[${fmt(lo)}, ${fmt(hi)}]</td></tr>`).join('')}</tbody></table></div></details><p class="ser-source">Source: <a href="${E(dataset.sourceUrl)}" target="_blank" rel="noopener noreferrer">${E(dataset.sourceLabel)} ↗</a>. Correlations do not establish causation. Pair-specific sample sizes are not provided in this table.</p></div>`;}
function home(old){const rows=[...old.matchAll(/<article class="publication-row"[\s\S]*?<\/article>/g)].map(m=>m[0]).join('');assert.ok(rows,'Home publication records missing');
 const director=old.match(/<section class="person-director">[\s\S]*?<\/section>/)?.[0];assert.ok(director,'Director biography missing');
 const focus=old.match(/<section class="container home-focus"[\s\S]*?<\/section>/)?.[0]||'';
 const resources=old.match(/<section class="section container"[^>]*>(?:(?!<section)[\s\S])*?Useful links(?:(?!<section)[\s\S])*?<\/section>/)?.[0]||'';
 const notes=load('posts').slice(0,3).map(p=>`<article class="ser-note"><p class="eyebrow">${E(p.category)}</p><h3><a href="./blog/${E(p.slug)}.html">${E(p.title)}</a></h3><p>${E(p.deck)}</p>${link('./blog/'+E(p.slug)+'.html','Read summary')}</article>`).join('');
 return `<section class="ser-hero container"><div><p class="eyebrow">Department of Psychology · Ariel University</p><h1>Social Experiences,<br>Resilience, and Identity</h1><p class="ser-tagline">${E(site.tagline)}</p><p class="ser-intro">${E(site.introduction)}</p><div class="ser-actions"><a class="button" href="./research.html">Our research <span aria-hidden="true">→</span></a>${link('./about.html','About the lab')}</div></div><figure class="ser-hero-figure"><div class="ser-photo-frame"><img src="./assets/images/campus-library.jpg" width="1280" height="960" fetchpriority="high" alt="The Dr. Reuben Hecht Library at Ariel University, framed by leafy trees."></div><figcaption><span>Ariel University · Dr. Reuben Hecht Library</span><a href="./image-credits.html">Photo credit ↗</a></figcaption></figure></section><div class="container ser-lab-line"><span><span class="ser-status-dot" aria-hidden="true"></span>Directed by Dr. Maor Shani</span><span>Surveys · Experiments · Longitudinal &amp; qualitative research</span><span>Opening October 2026</span></div>
 <section class="container ser-section"><div class="section-heading"><div><p class="eyebrow">Our research</p><h2>Research areas</h2></div>${link('./research.html','All projects')}</div><div class="ser-areas">${[['Antisemitism and discrimination','Antisemitic experiences, prejudice, coping, social participation, and psychosocial health.','antisemitism.html'],['Intergroup relations and conflict','Political emotions, hope for peace and victory, social norms, cooperation, and coexistence.','projects/hope-conflict.html'],['Health and well-being','Illness identity, stigma, social support, and adaptation to chronic health conditions.','projects/illness-identity.html']].map(([t,d,u])=>`<article><h3>${t}</h3><p>${d}</p>${link('./'+u,'Explore this research')}</article>`).join('')}</div></section>
 <section class="ser-spotlight"><div class="container ser-spotlight-layout"><div><p class="eyebrow">Featured research</p><h2>Antisemitism and psychosocial health</h2><p>${E(projects[0].question)}</p><p>Our research with Jews in Germany examines experiences of antisemitism, vigilance, identification, coping, and participation.</p>${link('./projects/antisemitism-health.html','Read about the project')}</div>${chart('home')}</div></section>
 <section class="container ser-section ser-home-papers"><div class="section-heading"><div><p class="eyebrow">Publications</p><h2>Selected papers</h2></div>${link('./publications.html','All publications')}</div>${rows}</section>
 <section class="container ser-section"><div class="section-heading"><div><p class="eyebrow">From our research</p><h2>Research notes</h2></div>${link('./blog.html','All notes')}</div><div class="ser-notes">${notes}</div></section>
 <div class="container ser-home-director">${director}</div>${focus}${resources}<div class="container ser-closing"><h2>Research, teaching, and collaboration</h2><p>Explore current supervision opportunities, learn about participating in research, or get in touch.</p><div class="ser-actions">${link('./supervision.html','Supervision')}${link('./participate.html','Participate')}${link('./contact.html','Contact the lab')}</div></div>`;}
function project(old,p){const rows=[...old.matchAll(/<article class="publication-row"[\s\S]*?<\/article>/g)].map(m=>m[0]).join('');const germany=p.id==='antisemitism-health';const sourceNote=germany?`<p class="ser-method-note"><strong>About these data.</strong> ${E(dataset.description.replace(/^All ten variables and 45 unique correlations from the published table. /,''))} ${E(dataset.method)} These survey data predate October 7.</p>`:'';
 const toc=[['overview','Overview'],['approach','Research approach'],...(germany?[['findings','Published findings']]:[]),['publications','Related publications'],['contact','Get in touch']];
 return `<div class="container"><nav class="ser-breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Home</a><span aria-hidden="true">/</span><a href="../research.html">Research</a><span aria-hidden="true">/</span><span aria-current="page">${E(p.title)}</span></nav><section class="ser-project-hero"><div><p class="eyebrow">${E(p.topic)}</p><h1>${E(p.title)}</h1><p class="lead">${E(p.question)}</p></div><aside class="ser-facts" aria-label="Project information"><dl><dt>Research area</dt><dd>${E(p.topic)}</dd><dt>Methods</dt><dd>${E(p.methods)}</dd><dt>Status</dt><dd>${E(p.status)}</dd></dl></aside></section><div class="ser-article-layout"><nav class="ser-contents" aria-label="On this page"><p>On this page</p>${toc.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}<a href="../people.html">Meet our students</a></nav><div class="ser-article-body"><section id="overview"><h2>Overview</h2><p>${E(p.summary)}</p></section><section id="approach"><h2>Research approach</h2><p>${E(p.methods)}.</p><p>This project overview explains the research direction; it does not present unpublished estimates or participant-level data.</p></section>${germany?`<section id="findings"><h2>Published findings</h2><p>Choose a measure to compare its reported correlations with psychosocial outcomes.</p>${chart('project')}${sourceNote}<p>${link('../data.html','Explore the full published correlation matrix')}</p></section>`:''}<section id="publications"><h2>Related publications</h2>${rows||'<p class="notice">This is ongoing research or evidence synthesis. No unpublished findings are presented here.</p>'}</section><section id="contact"><h2>Get in touch</h2><p>For collaboration or thesis research related to this project, contact the lab.</p><div class="ser-actions">${link('../contact.html','Discuss collaboration')}${link('../supervision.html','Thesis supervision')}</div></section></div></div><div class="ser-closing">${link('../research.html','Back to all research projects')}</div></div>`;}
const primary=[['research','Research'],['publications','Publications'],['people','People'],['teaching','Teaching']];
const secondary=[['antisemitism','Antisemitism research'],['supervision','Supervision'],['blog','Research summaries'],['data','Data explorer'],['explore','Reported findings'],['resources','Useful links'],['media','Media'],['conferences','Conferences & talks'],['ask','Ask the lab'],['about','About Maor'],['join','Join the lab'],['participate','Participate']];
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const files=walk(out).filter(f=>f.endsWith('.html'));
for(const file of files){let html=fs.readFileSync(file,'utf8');const original=html;const rel=path.relative(out,file).replaceAll(path.sep,'/'),slug=rel.replace(/\.html$/,'');const base=html.match(/data-base="([^"]+)"/)?.[1];assert.ok(base,'Missing route base');
 const navLink=([p,t])=>`<a href="${base+p}.html"${slug===p||slug.startsWith(p+'/')?' aria-current="page"':''}>${t}</a>`;
 const nav=`<nav id="main-nav" class="nav" aria-label="Main navigation">${primary.map(navLink).join('')}<details class="nav-more"><summary aria-controls="nav-explore">More</summary><ul id="nav-explore" class="nav-explore">${secondary.map(x=>'<li>'+navLink(x)+'</li>').join('')}</ul></details><a class="nav-contact" href="${base}contact.html"${slug==='contact'?' aria-current="page"':''}>Contact</a></nav>`;
 html=once(html,/<nav id="main-nav"[\s\S]*?<\/nav>/,()=>nav,'navigation');
 html=once(html,/<\/head>/,()=>`<link rel="stylesheet" href="${base}assets/elegant.css"><script defer src="${base}assets/elegant.js"></script></head>`,'head');
 html=html.replace('<body ',`<body data-design="elegant" data-page="${E(slug)}" `);
 if(slug==='index')html=once(html,/<main id="main"[^>]*>[\s\S]*?<\/main>/,()=>`<main id="main" tabindex="-1">${home(original)}</main>`,'home main');
 const p=projects.find(p=>slug==='projects/'+p.id);
 if(p)html=once(html,/<main id="main"[^>]*>[\s\S]*?<\/main>/,()=>`<main id="main" tabindex="-1">${project(original,p)}</main>`,'project main');
 // Preserve every generated form and every publication action in the rewritten views.
 for(const form of original.matchAll(/<form\b[\s\S]*?<\/form>/g))assert.ok(html.includes(form[0]),'A form was altered: '+slug);
 for(const token of original.matchAll(/\bdata-(?:copy|bib)="[^"]*"/g))assert.ok(html.includes(token[0]),'A citation action was lost: '+slug);
 assert.equal((html.match(/<h1\b/g)||[]).length,1,'Expected one H1: '+slug);
 assert.ok(html.includes(`data-mode="${process.argv.includes('--production')?'production':'review'}"`),'Form mode changed');
 fs.writeFileSync(file,html);
}
console.log(`Applied the approved elegant layout to ${files.length} pages; content, citations and forms preserved.`);
