export function focusPages({page,intro,H,E,ext,button,site,pubs,antisemitism,teaching}){
 const contact=(title,text)=>`<section class="container focus-contact"><div><div class="eyebrow">Start a conversation</div><h2>${E(title)}</h2><p>${E(text)}</p></div><div class="focus-contact-actions">${button('contact','Contact the lab')}<a class="text-link" href="mailto:${E(site.email)}">${E(site.email)}</a></div></section>`;
 page('antisemitism','Antisemitism research','Research on antisemitism, Jewish and Israeli experiences, discrimination, coping, and resilience at SERI Lab.',()=>`
 ${intro('A central research area','Antisemitism research',antisemitism.lead)}
 <div class="container"><nav class="section-jump" aria-label="Antisemitism research sections"><a href="#published">Published work</a><a href="#ongoing">Ongoing research</a><a href="#research-teaching">Research & teaching</a></nav><p class="focus-introduction">${E(antisemitism.introduction)}</p></div>
 <section class="container focus-section" id="published"><div class="section-top"><h2>Published work</h2></div><div class="publication-features">${antisemitism.published.map(item=>{const p=pubs.find(p=>p.id===item.publication);if(!p||p.forthcoming)throw Error('Published feature must reference an existing published record: '+item.publication);return `<article class="publication-feature"><div class="eyebrow">${E(item.label)}</div><h3>${E(item.heading)}</h3><p>${E(item.description)}</p><details class="publication-citation"><summary>Publication details</summary><p>${E(p.authors)} (${p.year}). ${E(p.title)}. <em>${E(p.venue)}</em>.</p><a href="${H('publications')}#${E(p.id)}">View in the publication library</a></details><div class="actions">${ext(p.url,p.type==='article'?'Read the article':p.type==='chapter'?'View the chapter':'Read the report','text-link')}</div></article>`;}).join('')}</div><p class="focus-related">Explore the <a href="${H('data')}">published correlation matrix</a>, or browse our <a href="${H('publications')}">publication library</a>.</p></section>
 <section class="focus-band" id="ongoing"><div class="container"><div class="eyebrow">Current directions</div><h2>Ongoing research</h2><div class="focus-grid">${antisemitism.ongoing.map(item=>`<article class="focus-topic"><h3>${E(item.title)}</h3><p>${E(item.description)}</p></article>`).join('')}</div><div class="focus-development"><h3>In development</h3><p>${E(antisemitism.development)}</p></div></div></section>
 <section class="container focus-section research-teaching" id="research-teaching"><div><div class="eyebrow">From research to the classroom</div><h2>Antisemitism and Trauma</h2></div><div><p>Our Ariel University seminar connects these questions with student learning and empirical research on discrimination, coping, and resilience.</p><a class="text-link" href="${H('teaching')}#antisemitism-trauma">Explore the seminar <span aria-hidden="true">→</span></a></div></section>
 ${contact('Let’s talk about the research',antisemitism.invitation)}`);
 const course=item=>`<article class="course-card"><h3>${E(item.title)}</h3>${item.period?`<p class="course-period">${E(item.period)}</p>`:''}<p>${E(item.description)}</p></article>`;
 page('teaching','Teaching','Dr. Maor Shani’s teaching philosophy, Antisemitism and Trauma seminar, and courses at Ariel University and Osnabrück University.',()=>`
 ${intro('Inquiry, evidence, and experience','Teaching',teaching.lead)}
 <div class="container"><nav class="section-jump" aria-label="Teaching sections"><a href="#approach">Our approach</a><a href="#antisemitism-trauma">Antisemitism & trauma</a><a href="#ariel-courses">Ariel University</a><a href="#osnabrueck-courses">Osnabrück University</a></nav></div>
 <section class="container focus-section" id="approach"><h2>Learning to ask better questions</h2><p class="focus-introduction">${E(teaching.philosophy)}</p><div class="teaching-principles">${teaching.principles.map(p=>`<div><h3>${E(p.title)}</h3><p>${E(p.text)}</p></div>`).join('')}</div></section>
 <section class="seminar-feature" id="antisemitism-trauma"><div class="container seminar-grid"><div><div class="eyebrow">Featured seminar · Ariel University</div><h2>${E(teaching.seminar.title)}</h2><p class="seminar-subtitle">${E(teaching.seminar.subtitle)}</p><p class="course-period">${E(teaching.seminar.period)}</p><a class="text-link" href="${H('antisemitism')}">Explore our antisemitism research <span aria-hidden="true">→</span></a></div><div><p>${E(teaching.seminar.description)}</p><p>${E(teaching.seminar.practice)}</p><p class="seminar-discussion">${E(teaching.seminar.discussion)}</p></div></div></section>
 <section class="container focus-section" id="ariel-courses"><div class="eyebrow">2025–26 & plans for 2026–27</div><h2>Teaching at Ariel University</h2><div class="course-grid">${teaching.ariel.map(course).join('')}</div></section>
 <section class="container focus-section past-teaching" id="osnabrueck-courses"><div class="eyebrow">Selected courses · 2020–25</div><h2>Teaching at Osnabrück University</h2><p class="focus-introduction">During his postdoctoral work, Maor taught undergraduate and master’s courses connecting developmental and social psychology with questions of identity, culture, and societal change.</p><div class="course-grid course-grid--past">${teaching.osnabrueck.map(course).join('')}</div></section>
 ${contact('Connect through teaching',teaching.invitation)}`);
}
